import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Nav from "@/components/nav";

export const metadata: Metadata = {
  title: "TypeTrainer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-open_sans m-0 p-0 bg-background">
        <Nav />
        {children}
      </body>
    </html>
  );
}
